# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pod_name", models.CharField(db_index=True, max_length=255)),
                ("namespace", models.CharField(db_index=True, max_length=255)),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("service_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("incident_type", models.CharField(choices=[("CrashLoopBackOff", "CrashLoopBackOff"), ("OOMKill", "OOMKill"), ("NodePressure", "NodePressure"), ("ImagePullBackOff", "ImagePullBackOff"), ("Evicted", "Evicted"), ("Pending", "Pending"), ("Unknown", "Unknown")], max_length=50)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("investigating", "Investigating"), ("resolved", "Resolved")], default="open", max_length=20)),
                ("description", models.TextField()),
                ("raw_logs", models.TextField(blank=True)),
                ("ai_analysis", models.TextField(blank=True)),
                ("chroma_id", models.CharField(blank=True, max_length=255)),
                ("neo4j_id", models.CharField(blank=True, max_length=255)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ClusterPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pod_name", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=255)),
                ("incident_type", models.CharField(max_length=50)),
                ("frequency", models.IntegerField(default=0)),
                ("best_fix", models.TextField(blank=True)),
                ("fix_success_rate", models.FloatField(default=0.0)),
                ("last_seen", models.DateTimeField()),
            ],
            options={
                "ordering": ["-frequency"],
                "unique_together": {("pod_name", "namespace", "incident_type")},
            },
        ),
        migrations.CreateModel(
            name="Fix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("applied_by", models.CharField(max_length=255)),
                ("worked", models.BooleanField(default=False)),
                ("ai_suggested", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("correction_of", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="incidents.fix")),
                ("incident", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fixes", to="incidents.incident")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
