# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClusterConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("connection_method", models.CharField(choices=[("kubeconfig", "Kubeconfig File"), ("in_cluster", "In-Cluster (Pod)"), ("context", "Kubeconfig Context")], max_length=20)),
                ("kubeconfig_path", models.CharField(blank=True, max_length=512)),
                ("context_name", models.CharField(blank=True, max_length=255)),
                ("namespaces", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("connected", "Connected"), ("failed", "Failed"), ("watching", "Watching Events")], default="pending", max_length=20)),
                ("server_version", models.CharField(blank=True, max_length=50)),
                ("node_count", models.IntegerField(default=0)),
                ("last_connected", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
